services:
  app:
    build: .
    container_name: courts-uptime
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./courts.csv:/app/courts.csv
      - ./proxy:/app/proxy:ro
    restart: unless-stopped
