[project]
name = "courts-probe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "charset-normalizer>=3.4.3",
    "httpx>=0.28.1",
    "lxml>=6.0.1",
    "pyyml>=0.0.2",
    "tenacity>=9.1.2",
]
