global:
  scrape_interval: 60s
  scrape_timeout: 10s
  evaluation_interval: 60s
  external_labels:
    monitor: "court-uptime"

scrape_configs:
  # Метрики самого blackbox
  - job_name: "blackbox"
    static_configs:
      - targets: ["blackbox:9115"]

  # Через proxy0
  - job_name: "probe_http_head_via_proxy0"
    metrics_path: /probe
    params:
      module: [http_head_via_proxy1]
    file_sd_configs:
      - files: ["/etc/prometheus/targets/proxy0.yml"]
        refresh_interval: 2m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
      - source_labels: [__param_target]
        target_label: instance
    scrape_interval: 1m
    scrape_timeout: 10s

  # Через proxy1
  - job_name: "probe_http_head_via_proxy1"
    metrics_path: /probe
    params:
      module: [http_head_via_proxy1]
    file_sd_configs:
      - files: ["/etc/prometheus/targets/proxy1.yml"]
        refresh_interval: 2m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
      - source_labels: [__param_target]
        target_label: instance
    scrape_interval: 1m
    scrape_timeout: 10s

  # Через proxy2
  - job_name: "probe_http_head_via_proxy2"
    metrics_path: /probe
    params:
      module: [http_head_via_proxy1]
    file_sd_configs:
      - files: ["/etc/prometheus/targets/proxy2.yml"]
        refresh_interval: 2m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
      - source_labels: [__param_target]
        target_label: instance
    scrape_interval: 1m
    scrape_timeout: 10s

  # Через proxy3
  - job_name: "probe_http_head_via_proxy3"
    metrics_path: /probe
    params:
      module: [http_head_via_proxy2]
    file_sd_configs:
      - files: ["/etc/prometheus/targets/proxy3.yml"]
        refresh_interval: 2m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
      - source_labels: [__param_target]
        target_label: instance
    scrape_interval: 1m
    scrape_timeout: 10s

#  # GET + keyword для «капризных»
#  - job_name: "probe_http_get_keyword_via_proxy1"
#    metrics_path: /probe
#    params:
#      module: [http_get_keyword_via_proxy1]
#    file_sd_configs:
#      - files: ["/etc/prometheus/targets/keyword.yml"]
#        refresh_interval: 2m
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - target_label: __address__
#        replacement: blackbox:9115
#      - source_labels: [__param_target]
#        target_label: instance
#    scrape_interval: 3m
#    scrape_timeout: 12s
